### ISSUE TITLE
New Wuolah adds bug

### ISSUE THREAD

**Issue by 0xCAB0** [YM162/gulagcleaner#14]
It seems like Wuolah has uploaded a new kind of *in-page* add that the cleaner is not handling correctly and its returning a blank page.

It should have been fixed by #9 but keep getting this bug.

### Tested for

- [x]  Web environment 

- [x] Rust crate

## Page with adds
![image](https://github.com/YM162/gulagcleaner/assets/74014545/dc81ddcd-fd50-41cb-95f9-e7bc7b54fdcc)

## Page after cleaning process
![image](https://github.com/YM162/gulagcleaner/assets/74014545/de1feca4-45fa-4398-8460-082ca2e0663c)

## Original document

[wuolah-free-Apuntes-Tasaciones-y-Valoraciones[1].pdf](https://github.com/YM162/gulagcleaner/files/13927797/wuolah-free-Apuntes-Tasaciones-y-Valoraciones.1.pdf)

**Comment by MiniRomer** [comment]
I get corrupted file after running it through.

**Comment by dirudomelon** [comment]
pdf corrupted :(

**Comment by YM162** [comment]
Looking at it right now.

**Comment by YM162** [comment]
They just used this type of page for a couple of days, so I don't think we need to work on it for the moment
