### ISSUE TITLE
Clean PDF Bytes Not Pushed to PyPI

### ISSUE THREAD

**Issue by shubhamshah02** [YM162/gulagcleaner#19]
On the latest version of Gulagcleaner on PyPI, the clean_pdf_bytes function is unavailable in the clean.py file. Please update this!

**Comment by YM162** [comment]
It seems there was a small problem with the automated publishing, should be fixed now with  [v0.14.1](https://github.com/YM162/gulagcleaner/releases/v0.14.1)
