### ISSUE TITLE
Corrupted file when downloading from web

### ISSUE THREAD

**Issue by Albetroz** [YM162/gulagcleaner#20]
I uploaded file from Wuolah to GulagCleaner, and the output file was damaged and couldn't be opened. I tried with several other files and they didn't work either. It seems that Wuolah changed the way ads are added to PDF files in Wuolah. Here you have both files, if you need them:

[wuolah-premium-Resumen-completo-Tema-5.pdf](https://github.com/user-attachments/files/15517590/wuolah-premium-Resumen-completo-Tema-5.pdf)

[wuolah-premium-Resumen-completo-Tema-5-gulag-free.pdf](https://github.com/user-attachments/files/15517585/wuolah-premium-Resumen-completo-Tema-5-gulag-free.pdf)

**Comment by YM162** [comment]
Thanks for the warning! It should be fixed now with [v0.14.1](https://github.com/YM162/gulagcleaner/releases/v0.14.1) :)
