### ISSUE TITLE
Empty pdf

### ISSUE THREAD

**Issue by pgalinanes** [YM162/gulagcleaner#26]
Using the new version from the web results in empty pdf file.
This pdf can replicate the error:
[wuolah-free-TEMA-2-ENVEJECIMIENTO-BASES-MOLECULARES-DE-LAS-ENFERMEDADES-NEURODEGENERATIVAS.pdf](https://github.com/user-attachments/files/17188047/wuolah-free-TEMA-2-ENVEJECIMIENTO-BASES-MOLECULARES-DE-LAS-ENFERMEDADES-NEURODEGENERATIVAS.pdf)

**Comment by YM162** [comment]
It looks like newer PDFs have a flat /Contents dictionary, so we cannot use the normal Wuolah method anymore. 

In the short term we should improve the Naive method: Now in [page_type.rs](https://github.com/YM162/gulagcleaner/blob/main/gulagcleaner_rs/src/models/page_type.rs) we are determining the type of the PDF page using the pixel size of the images, but any small change in these sizes makes the ads escape the detection mechanism.
Any of these would improve the detection:
* Check the height:width ratio of the images.
* Compare the width/height of the images to the width/height of the page (They go from one border to the other).

There are probably other smarter ways to do it, but this should be enough to at least make it work again.

If anyone has the time to implement it, any of these changes would be greatly appreciated!

**Comment by luisgythub** [comment]
Even with the newest version (0.14.4) the PDFs appear to be damaged. Is there any way to fix it?

**Comment by luisgythub** [comment]
> Even with the newest version (0.14.4) the PDFs still appear to be damaged. Is there any way to fix it?

Thank you so much, it is now fixed

**Comment by YM162** [comment]
Thanks for the heads up! 

This issue should be fixed with version 0.14.6, at least for the latest PDFs :)
