### ISSUE TITLE
some PDFs get cut incorrectly

### ISSUE THREAD

**Issue by tooanri4you** [YM162/gulagcleaner#27]
Not sure what's causing this nor why it happens to some PDFs and it doesn't happen to others, but I'm pretty sure this happens to uploads of the past year, stuff that's older seems to come out just fine. Tested this just now, I'll attach some examples below

[wuolah-premium-Antropologia-definitivo.pdf](https://github.com/user-attachments/files/17325683/wuolah-premium-Antropologia-definitivo.pdf) this comes out as 
[wuolah-premium-Antropologia-definitivo-gulag-free.pdf](https://github.com/user-attachments/files/17325825/wuolah-premium-Antropologia-definitivo-gulag-free.pdf)

[wuolah-premium-EMBRIOLOGIA-1.pdf](https://github.com/user-attachments/files/17325882/wuolah-premium-EMBRIOLOGIA-1.pdf) comes out as 
[wuolah-premium-EMBRIOLOGIA-1-gulag-free.pdf](https://github.com/user-attachments/files/17325920/wuolah-premium-EMBRIOLOGIA-1-gulag-free.pdf)

**Comment by kikitor918** [comment]
Me pasa lo mismo

**Comment by luisgythub** [comment]
It was working just fine a couple of versions ago (14.6), but it seems the current code overestimates the height - width of the adds. I think it applies the same changes to all pages regardless of whether they have adds or not. It also doesn’t recognise the logo at the bottom. Don’t really know if the changes were intended to fix issues with a certain type of Wuolah documents (the ones listed as examples in the new actualisation), but from what I’m seeing, they aren’t working on most documents.

**Comment by YM162** [comment]
I'm pretty sure I just fixed this with the last commit. 

I'll test it a bit more later and hopefully tomorrow I'll make a new release :)

**Comment by YM162** [comment]
The latest release v0.15.0 should fix this. 👍🏻
