### ISSUE TITLE
Gulagcleaner removes pages from pdfs

### ISSUE THREAD

**Issue by martinac72** [YM162/gulagcleaner#28]
Gulagcleaner removes pages with ads at the top and left of the page. In addition, PDFs show an error when opening them with Acrobat Reader, although they can be viewed without problems.

Here is an example:

[wuolah-premium-Fisica.pdf](https://github.com/user-attachments/files/17579203/wuolah-premium-Fisica.pdf)

[wuolah-premium-Fisica-gulag-free.pdf](https://github.com/user-attachments/files/17579206/wuolah-premium-Fisica-gulag-free.pdf)

It removes, pages 1,4,7,10,13 and 16. This is the error it show when you open the pdf in Acrobat Reader:

![image](https://github.com/user-attachments/assets/09208cd5-767d-4fa9-a1d7-0c8c76a919c2)

**Comment by martinac72** [comment]
@gongchandang49, i have checked your tool, and it works better, it doesn't remove the wrong pages. One thing to improve it is check the orientation of the page before deleting the ads. This way, it doesn't convert A4 landscape pages to A4 portrait pages. This happens is both methods: basic and normal. You can check it with the documents i have uplodaded. Thx

**Comment by YM162** [comment]
Should be fixed with #31 and #33
